name: the_tipster

packages:
  - .
  - modules/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  fast:
    run: |
      melos clean:all
      melos bootstrap
    description: "Run `flutter pub get` in all packages."

  analyze:
    run: melos exec --scope=* -c 4 -- \
      flutter analyze --no-fatal-infos --no-fatal-warnings --no-pub
    description: Run `flutter analyze` in all modules.

  clean:all:
    run: |
      dart clean
      rm -rf .dart_tool
      rm -rf .idea
      rm -rf .packages
      rm -rf build
      rm -rf ios/.symlinks
      rm -rf ios/Flutter/Flutter.framework
      rm -rf ios/Flutter/Flutter.podspec
      rm -rf ios/ServiceDefinitions.json
      rm -rf android/.gradle
      rm -rf android/app/build
    description: "Clean the build artifacts and caches in all packages."